#include "system/includes.h"
#include "app_config.h"
#include "rider_core_temp.h"

#define LOG_TAG_CONST       RIDER_ESTIMATOR
#define LOG_TAG             "[RIDER_ESTIMATOR]"
#define LOG_INFO_ENABLE
#include "debug.h"

#if CONFIG_APP_RIDER_CORE_TEMP

static rider_temperature_snapshot_t rider_snapshot;
static rider_core_temperature_calibration_t rider_calibration;
static int16_t rider_core_model_centi;
static u8 rider_core_model_initialized;
static uint32_t rider_estimator_last_tick_sequence;
static u8 rider_estimator_missing_ticks;

/** Reset the dynamic state of the single-sensor core model. */
static void rider_estimator_reset_core_model(void)
{
    rider_core_model_centi = 0x7fff;
    rider_core_model_initialized = 0;
}

/** Clamp a candidate core estimate to the physiologically bounded model range. */
static int16_t rider_estimator_clamp_core(int32_t candidate)
{
    if (candidate < RIDER_CORE_TEMP_ESTIMATE_MIN_CENTI) {
        return RIDER_CORE_TEMP_ESTIMATE_MIN_CENTI;
    }
    if (candidate > RIDER_CORE_TEMP_ESTIMATE_MAX_CENTI) {
        return RIDER_CORE_TEMP_ESTIMATE_MAX_CENTI;
    }
    return (int16_t)candidate;
}

/** Apply a signed Q8 step without relying on implementation-defined shifts. */
static int16_t rider_estimator_q8_step(int16_t previous, int32_t target,
                                       uint8_t alpha_q8)
{
    int32_t delta = target - previous;
    int32_t step = delta * alpha_q8;

    if (step >= 0) {
        step = (step + 128) / 256;
    } else {
        step = -(((-step) + 128) / 256);
    }
    return rider_estimator_clamp_core((int32_t)previous + step);
}

/** Limit one-second changes before publishing a physiological estimate. */
static int16_t rider_estimator_limit_rate(int16_t previous, int16_t candidate)
{
    int32_t delta = (int32_t)candidate - previous;

    if (delta > RIDER_CORE_TEMP_ESTIMATE_MAX_STEP_CENTI) {
        return (int16_t)(previous + RIDER_CORE_TEMP_ESTIMATE_MAX_STEP_CENTI);
    }
    if (delta < -RIDER_CORE_TEMP_ESTIMATE_MAX_STEP_CENTI) {
        return (int16_t)(previous - RIDER_CORE_TEMP_ESTIMATE_MAX_STEP_CENTI);
    }
    return candidate;
}

/** Load the compile-time calibration generated by the offline tool. */
static void rider_estimator_load_default_calibration(void)
{
    rider_calibration.offset_centi = RIDER_CORE_TEMP_CAL_OFFSET_CENTI;
    rider_calibration.slope_gain_q8 = RIDER_CORE_TEMP_CAL_SLOPE_GAIN_Q8;
    rider_calibration.lag_alpha_q8 = RIDER_CORE_TEMP_CAL_LAG_ALPHA_Q8;
    rider_calibration.available = RIDER_CORE_TEMP_CALIBRATION_AVAILABLE ? 1 : 0;
    rider_calibration.valid = RIDER_CORE_TEMP_CALIBRATION_VALID ? 1 : 0;
#if RIDER_CORE_TEMP_PUBLISH_MODE == RIDER_CORE_TEMP_PUBLISH_EXPERIMENTAL
    /* Collection mode must expose a deterministic candidate before a
     * physiological offset is available. It uses the filtered multi-sample
     * skin signal with the same lag/limit model; calibration can replace it
     * later without changing the BLE contract. */
    rider_calibration.available = 1;
#endif
}

/** Clear all measurement channels while preserving the current sequence/HR. */
static void rider_estimator_clear_measurement(uint8_t status, uint8_t state)
{
    rider_snapshot.valid = 0;
    rider_snapshot.contact_valid = 0;
    rider_snapshot.skin_valid = 0;
    rider_snapshot.core_estimate_valid = 0;
    rider_snapshot.core_estimate_verified = 0;
    rider_snapshot.contact_temperature_centi = 0x7fff;
    rider_snapshot.skin_temperature_centi = 0x7fff;
    rider_snapshot.core_temperature_centi = 0x7fff;
    rider_snapshot.slope_centi_per_min = 0;
    rider_snapshot.quality = RIDER_TEMP_QUALITY_NA;
    rider_snapshot.confidence = 0;
    rider_snapshot.sensor_status = status;
    rider_snapshot.temperature_state = state;
    rider_snapshot.data_freshness = state == RIDER_TEMP_STATE_STALE
                                        ? RIDER_TEMP_FRESHNESS_STALE
                                        : RIDER_TEMP_FRESHNESS_UNAVAILABLE;
    rider_estimator_reset_core_model();
}

/** Set the initial quality/confidence for a filtered contact measurement. */
static void rider_estimator_set_contact_quality(
    const rider_temperature_filter_output_t *filtered)
{
    rider_snapshot.quality = filtered->quality;
    if (filtered->state == RIDER_TEMP_STATE_STABLE) {
        rider_snapshot.confidence = filtered->quality == RIDER_TEMP_QUALITY_GOOD
                                         ? 70
                                         : 55;
    } else {
        rider_snapshot.confidence = 25;
    }
}

/** Update the calibrated first-order core estimate from one stable sample. */
static void rider_estimator_update_core_model(
    const rider_temperature_filter_output_t *filtered)
{
    int32_t target;
    int32_t slope_term;
    uint8_t alpha;

    if (!rider_calibration.available || !filtered || !filtered->valid ||
        filtered->state != RIDER_TEMP_STATE_STABLE ||
        filtered->quality < RIDER_TEMP_QUALITY_FAIR ||
        (RIDER_CORE_TEMP_PUBLISH_MODE == RIDER_CORE_TEMP_PUBLISH_STRICT &&
         filtered->quality < RIDER_TEMP_QUALITY_GOOD)) {
        rider_snapshot.core_estimate_valid = 0;
        rider_snapshot.core_estimate_verified = 0;
        rider_snapshot.core_temperature_centi = 0x7fff;
        rider_estimator_reset_core_model();
        return;
    }

    slope_term = (int32_t)filtered->slope_centi_per_min *
                 rider_calibration.slope_gain_q8;
    target = (int32_t)filtered->filtered_temperature_centi +
             rider_calibration.offset_centi + slope_term / 256;
    target = rider_estimator_clamp_core(target);
    alpha = rider_calibration.lag_alpha_q8;
    if (!alpha) {
        alpha = 1;
    }
    if (!rider_core_model_initialized) {
        rider_core_model_centi = (int16_t)target;
        rider_core_model_initialized = 1;
    } else {
        rider_core_model_centi = rider_estimator_limit_rate(
            rider_core_model_centi,
            rider_estimator_q8_step(rider_core_model_centi, target, alpha));
    }

    rider_snapshot.core_temperature_centi = rider_core_model_centi;
    rider_snapshot.confidence = rider_snapshot.confidence < 90
                                    ? (uint8_t)(rider_snapshot.confidence + 10)
                                    : 100;
    rider_snapshot.core_estimate_valid =
#if RIDER_CORE_TEMP_PUBLISH_MODE == RIDER_CORE_TEMP_PUBLISH_EXPERIMENTAL
        1;
#else
        rider_snapshot.confidence >= RIDER_CORE_TEMP_MIN_CONFIDENCE;
#endif
    rider_snapshot.core_estimate_verified = rider_snapshot.core_estimate_valid &&
                                            rider_calibration.valid;
    if (!rider_snapshot.core_estimate_valid) {
        rider_snapshot.core_temperature_centi = 0x7fff;
        rider_snapshot.core_estimate_verified = 0;
    }
}

/** Reset the protocol snapshot and start the product filter. */
void rider_estimator_init(void)
{
    memset(&rider_snapshot, 0, sizeof(rider_snapshot));
    rider_snapshot.contact_temperature_centi = 0x7fff;
    rider_snapshot.skin_temperature_centi = 0x7fff;
    rider_snapshot.core_temperature_centi = 0x7fff;
    rider_snapshot.quality = RIDER_TEMP_QUALITY_NA;
    rider_snapshot.sensor_status = RIDER_TEMP_STATUS_NO_DEVICE;
    rider_snapshot.temperature_state = RIDER_TEMP_STATE_NO_DEVICE;
    rider_snapshot.data_freshness = RIDER_TEMP_FRESHNESS_UNAVAILABLE;
    rider_estimator_load_default_calibration();
    rider_estimator_reset_core_model();
    rider_estimator_last_tick_sequence = 0;
    rider_estimator_missing_ticks = 0;
    rider_temp_filter_init();
    log_info("Estimator init: calibration_available=%u calibration_verified=%u "
             "publish_mode=%u core=NA skin=NA average=NA\n",
             (unsigned)rider_calibration.available,
             (unsigned)rider_calibration.valid,
             (unsigned)RIDER_CORE_TEMP_PUBLISH_MODE);
}

/**
 * Consume one validated M601 sample and publish filtered single-site skin
 * temperature. The core estimate is a separate model over these samples.
 *
 * EXPERIMENTAL mode exposes the numerical candidate after stability so the
 * product can compare it with real-world references. The candidate remains
 * explicitly unverified and is never treated as a medical measurement.
 */
void rider_estimator_consume(const rider_temperature_sample_t *sample)
{
    rider_temperature_filter_output_t filtered;

    rider_temp_filter_consume(sample, &filtered);
    rider_snapshot.sequence = filtered.sequence;
    rider_snapshot.sensor_status = filtered.status;
    rider_snapshot.temperature_state = filtered.state;
    rider_snapshot.data_freshness = filtered.freshness;
    rider_snapshot.slope_centi_per_min = filtered.slope_centi_per_min;

    if (!filtered.valid) {
        rider_estimator_clear_measurement(filtered.status, filtered.state);
        rider_snapshot.sequence = filtered.sequence;
        log_info("Estimator snapshot: seq=%u valid=0 status=%u state=%u "
                 "contact=NA skin=NA core=NA average=NA\n",
                 (unsigned)filtered.sequence, (unsigned)filtered.status,
                 (unsigned)filtered.state);
        return;
    }

    rider_snapshot.contact_temperature_centi =
        filtered.filtered_temperature_centi;
    rider_snapshot.contact_valid = 1;
    /* The wear window already rejects ambient values. Treat the filtered M601
     * contact value as the single-site skin temperature; core publication
     * below remains gated by the multi-sample stable state. */
    rider_snapshot.skin_valid = filtered.valid;
    rider_snapshot.skin_temperature_centi = rider_snapshot.skin_valid
                                                ? filtered.filtered_temperature_centi
                                                : 0x7fff;
    rider_snapshot.valid = 0;
    rider_snapshot.core_estimate_valid = 0;
    rider_snapshot.core_estimate_verified = 0;
    rider_snapshot.core_temperature_centi = 0x7fff;
    rider_estimator_set_contact_quality(&filtered);
    rider_estimator_update_core_model(&filtered);
#if RIDER_CORE_TEMP_PUBLISH_MODE == RIDER_CORE_TEMP_PUBLISH_STRICT
    rider_snapshot.valid = rider_snapshot.core_estimate_valid &&
                           rider_snapshot.core_estimate_verified;
#elif RIDER_CORE_TEMP_PUBLISH_MODE == RIDER_CORE_TEMP_PUBLISH_EXPERIMENTAL
    rider_snapshot.valid = rider_snapshot.core_estimate_valid &&
                           rider_snapshot.temperature_state ==
                               RIDER_TEMP_STATE_STABLE &&
                           rider_snapshot.data_freshness ==
                               RIDER_TEMP_FRESHNESS_FRESH;
#elif RIDER_CORE_TEMP_PUBLISH_MODE == RIDER_CORE_TEMP_PUBLISH_CONTACT_PROXY
    rider_snapshot.valid = rider_snapshot.contact_valid &&
                           rider_snapshot.temperature_state ==
                               RIDER_TEMP_STATE_STABLE &&
                           rider_snapshot.data_freshness ==
                               RIDER_TEMP_FRESHNESS_FRESH;
#else
    /* Shadow mode keeps all unvalidated estimates out of notifications. */
    rider_snapshot.valid = 0;
#endif

    log_info("Estimator snapshot: seq=%u valid=%u status=%u state=%u "
             "contact_centi=%d skin=%s core_est=%s verified=%s "
             "confidence=%u slope_cpm=%d\n",
             (unsigned)filtered.sequence, (unsigned)rider_snapshot.valid,
             (unsigned)rider_snapshot.sensor_status,
             (unsigned)rider_snapshot.temperature_state,
             (int)rider_snapshot.contact_temperature_centi,
             rider_snapshot.skin_valid ? "valid" : "NA",
             rider_snapshot.core_estimate_valid ? "valid" : "NA",
             rider_snapshot.core_estimate_verified ? "yes" : "no",
             (unsigned)rider_snapshot.confidence,
             (int)rider_snapshot.slope_centi_per_min);
}

/** Copy the current snapshot so GATT callbacks never mutate shared storage. */
void rider_estimator_copy_snapshot(rider_temperature_snapshot_t *snapshot)
{
    if (snapshot) {
        memcpy(snapshot, &rider_snapshot, sizeof(*snapshot));
    }
}

/**
 * Expire a stable snapshot when the conversion callback stops completing.
 *
 * A stuck conversion callback does not produce an invalid sample, so sequence
 * tracking alone would otherwise leave the last stable value publishable
 * forever. Expiration resets both estimator and filter; a later sample must
 * pass through the normal warming period again.
 */
void rider_estimator_tick(uint32_t latest_sequence)
{
    if (latest_sequence != rider_estimator_last_tick_sequence) {
        rider_estimator_last_tick_sequence = latest_sequence;
        rider_estimator_missing_ticks = 0;
        return;
    }

    if (rider_estimator_missing_ticks < 0xff) {
        rider_estimator_missing_ticks++;
    }
    if (rider_estimator_missing_ticks < RIDER_TEMP_STALE_AFTER_TICKS ||
        rider_snapshot.temperature_state == RIDER_TEMP_STATE_STALE ||
        (!rider_snapshot.contact_valid && !rider_snapshot.valid)) {
        return;
    }

    rider_temp_filter_init();
    rider_estimator_clear_measurement(RIDER_TEMP_STATUS_NO_DEVICE,
                                      RIDER_TEMP_STATE_STALE);
    rider_snapshot.sequence = latest_sequence;
    log_info("Estimator stale timeout: seq=%u ticks=%u state=%u\n",
             (unsigned)latest_sequence,
             (unsigned)rider_estimator_missing_ticks,
             (unsigned)rider_snapshot.temperature_state);
}

/** Install or clear a calibration generated by the host-side tool. */
void rider_estimator_set_core_calibration(
    const rider_core_temperature_calibration_t *calibration)
{
    if (!calibration) {
        rider_estimator_load_default_calibration();
    } else {
        rider_calibration = *calibration;
        rider_calibration.available = calibration->available || calibration->valid;
        rider_calibration.valid = calibration->valid ? 1 : 0;
    }
    rider_estimator_reset_core_model();
    rider_snapshot.core_estimate_valid = 0;
    rider_snapshot.core_estimate_verified = 0;
    rider_snapshot.core_temperature_centi = 0x7fff;
#if RIDER_CORE_TEMP_PUBLISH_MODE == RIDER_CORE_TEMP_PUBLISH_CONTACT_PROXY
    rider_snapshot.valid = rider_snapshot.contact_valid &&
                           rider_snapshot.temperature_state ==
                               RIDER_TEMP_STATE_STABLE &&
                           rider_snapshot.data_freshness ==
                               RIDER_TEMP_FRESHNESS_FRESH;
#elif RIDER_CORE_TEMP_PUBLISH_MODE == RIDER_CORE_TEMP_PUBLISH_EXPERIMENTAL
    rider_snapshot.valid = rider_snapshot.core_estimate_valid &&
                           rider_snapshot.temperature_state ==
                               RIDER_TEMP_STATE_STABLE &&
                           rider_snapshot.data_freshness ==
                               RIDER_TEMP_FRESHNESS_FRESH;
#else
    rider_snapshot.valid = 0;
#endif
    log_info("Estimator calibration: available=%u valid=%u offset=%d slope_gain_q8=%d "
             "lag_alpha_q8=%u\n",
             (unsigned)rider_calibration.available,
             (unsigned)rider_calibration.valid,
             (int)rider_calibration.offset_centi,
             (int)rider_calibration.slope_gain_q8,
             (unsigned)rider_calibration.lag_alpha_q8);
}

/** Store or clear the direct external heart-rate input from Control Point. */
void rider_estimator_set_external_heart_rate(uint8_t heart_rate, uint8_t valid)
{
    rider_snapshot.heart_rate = heart_rate;
    rider_snapshot.heart_rate_valid = valid ? 1 : 0;
}

#endif
